CREATE DATABASE MANTENIMIENTO_PRODUCTOS
USE MANTENIMIENTO_PRODUCTOS

CREATE TABLE CATEGORIA(
IDCATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO AS ('CT'+RIGHT ('00' + CONVERT(VARCHAR, IDCATEGORIA),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
DESCRIPCION NVARCHAR(256) NULL
)

INSERT INTO CATEGORIA VALUES ('HERRAMIENTAS','LAS MEJORES HERRAMIENTAS')
INSERT INTO CATEGORIA VALUES ('PINTORERIA','LAS MEJORES PINTURAS PARA TU CASA')

SELECT * FROM CATEGORIA