--PROCEDIMIENTO ALMACENADO BUSCAR CATEGORA

CREATE PROC SP_BUSCARCATEGORIA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CATEGORIA
WHERE NOMBRE LIKE @BUSCAR + '%'

--PROCEDIMIENTO ALMACENADO INSETAR CATEGORIA

CREATE PROC SP_INSERTARCATEGORIA
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
INSERT INTO CATEGORIA VALUES (@NOMBRE, @DESCRIPCION)

--PROCEDIMIENTO ALMACENADO EDITAR CATEGORA
CREATE PROC SP_EDITARCATEGORIA
@IDCATEGORIA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
UPDATE CATEGORIA SET NOMBRE = @NOMBRE, DESCRIPCION= @DESCRIPCION
WHERE IDCATEGORIA = @IDCATEGORIA

--PROCEDIMIENTO ALMACENADO ELIMINAR CATEGORIA
CREATE PROC SP_ELIMINARCATEGORIA
@IDCATEGORIA INT
AS
DELETE CATEGORIA
WHERE IDCATEGORIA=@IDCATEGORIA